### ISSUE TITLE
Feature Request - 'fake' filler tweets?

### ISSUE THREAD

**Issue by rachelnicole** [mbarlock/twitter-contest-bot#2]
I don't know if you've found that contests are biased / want you to tweet actual tweets, but if there's a concern at all, there could be a way to pull in a corpus of data to generate some filler tweets that make sense. 

Though, I guess this is more of an experiment with putting out a great frequency and seeing what you get in return?

**Comment by barlock** [comment]
I'm only passively familiar with twitter, I'm not actually sure what a lot of those contests are asking for other than for the "retweet" button to be clicked. I've attempted to filter out votes and when people ask questions you need to answer. Could you give examples of contests that want an actual tweet?

**Comment by rachelnicole** [comment]
I don't know if any examples to be honest. I just like making twitter bots so I was trying to think of extra features. :D
