### ISSUE TITLE
{ message: 'Rate limit exceeded', code: 88 }

### ISSUE THREAD

**Issue by calvinti12** [mbarlock/twitter-contest-bot#6]
Getting this error message even with new app Can you help
{ message: 'Rate limit exceeded', code: 88 }

**Comment by barlock** [comment]
Not maintaining this anymore. I'm not 100% sure what would be hitting a rate limit short of tweets. you could edit the config file to not send out so many tweets per day. How long is it taking to hit the rate limit? 

I think twitter also limits itself on what it sends you, you could narrow down what tweets your searching for as well.
